## Player Controller
##
## Generated by Player Scaffolder. Handles movement, camera, and interaction.
## Extend this script to add game-specific behaviour.
##
## @author KarnesTH
## @version 1.0
extends CharacterBody3D

@export_category("Movement")
@export var base_speed := 6.0
@export var sprint_multiplier := 1.5
@export var crouch_speed_multiplier := 0.5
@export var prone_speed_multiplier := 0.3
@export var jump_height := 1.2
@export var fall_multiplier := 2.5
@export var step_height := 0.3

@export_category("Camera")
@export var mouse_sensitivity: float = 0.00075
@export var camera_speed: float = 30.0
@export var pitch_min: float = -90.0
@export var pitch_max: float = 90.0
@export var lean_angle: float = 15.0
@export var lean_offset: float = 0.3
@export var lean_speed: float = 8.0

var gravity: float = ProjectSettings.get_setting("physics/3d/default_gravity")
var _look := Vector2.ZERO
var _lean_amount: float = 0.0
var _is_crouching := false
var _is_prone := false

@onready var camera: Camera3D = $Camera3D
@onready var camera_target: Node3D = $CameraTarget

## Called when the node enters the scene tree. Sets mouse to captured mode.
func _ready() -> void:
	Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)

## Smoothly interpolates the camera to follow the camera target each frame.
func _process(delta: float) -> void:
	camera.global_transform = camera.global_transform.interpolate_with(
		camera_target.global_transform, clamp(camera_speed * delta, 0.0, 1.0))
	camera.global_position = camera_target.global_position

## Handles movement, gravity, jumping, crouching, prone and step logic each physics tick.
func _physics_process(delta: float) -> void:
	_apply_camera_rotation()
	if not is_on_floor():
		if velocity.y >= 0 and Input.is_action_pressed("ui_accept"):
			velocity.y -= gravity * delta
		else:
			velocity.y -= gravity * delta * fall_multiplier
	if Input.is_action_just_pressed("jump") and is_on_floor():
		velocity.y = sqrt(jump_height * 2.0 * gravity)
	_check_step()
	_handle_lean(delta)
	var direction := _get_movement_direction()
	var speed := base_speed
	if Input.is_action_pressed("sprint"): speed *= sprint_multiplier
	if _is_crouching: speed *= crouch_speed_multiplier
	if _is_prone: speed *= prone_speed_multiplier
	if direction:
		velocity.x = lerp(velocity.x, direction.x * speed, speed * delta)
		velocity.z = lerp(velocity.z, direction.z * speed, speed * delta)
	else:
		velocity.x = move_toward(velocity.x, 0, speed * delta * 5.0)
		velocity.z = move_toward(velocity.z, 0, speed * delta * 5.0)
	if Input.is_action_just_pressed("crouch"):
		_toggle_crouch()
	if Input.is_action_just_pressed("prone"):
		_toggle_prone()
	move_and_slide()

## Returns the locally oriented movement direction based on input.
func _get_movement_direction() -> Vector3:
	var input_dir := Input.get_vector("move_left", "move_right", "move_forward", "move_back")
	return (transform.basis * Vector3(input_dir.x, 0, input_dir.y)).normalized()

## Applies mouse look rotation to the player and camera target.
func _apply_camera_rotation() -> void:
	rotate_y(_look.x)
	camera_target.rotate_x(_look.y)
	camera_target.rotation.x = clamp(camera_target.rotation.x, deg_to_rad(pitch_min), deg_to_rad(pitch_max))
	_look = Vector2.ZERO

## Toggles crouch state, adjusting CollisionShape and camera height.
func _toggle_crouch() -> void:
	_is_crouching = not _is_crouching
	var col := $CollisionShape3D
	var capsule := col.shape as CapsuleShape3D
	if _is_crouching:
		capsule.height = 1.0
		col.position.y = 0.5
		camera_target.position.y = 0.9
	else:
		capsule.height = 1.8
		col.position.y = 0.9
		camera_target.position.y = 1.6

## Toggles prone state, adjusting CollisionShape and camera height.
## Exits crouch first if active.
func _toggle_prone() -> void:
	if _is_crouching:
		_toggle_crouch()
	_is_prone = not _is_prone
	var col := $CollisionShape3D
	var capsule := col.shape as CapsuleShape3D
	if _is_prone:
		capsule.height = 0.5
		col.position.y = 0.25
		camera_target.position.y = 0.3
	else:
		capsule.height = 1.8
		col.position.y = 0.9
		camera_target.position.y = 1.6

## Checks for small steps ahead and nudges the player upward to climb them.
## Only active when on the floor and moving.
func _check_step() -> void:
	if velocity.length() < 0.1 or not is_on_floor():
		return
	var forward := -global_transform.basis.z.normalized()
	var step_origin := global_position + forward * 0.4
	var space := get_world_3d().direct_space_state
	var ray_down := PhysicsRayQueryParameters3D.create(
		step_origin + Vector3.UP * step_height,
		step_origin + Vector3.DOWN * 0.05,
		collision_mask
	)
	ray_down.exclude = [self]
	var hit := space.intersect_ray(ray_down)
	if hit:
		var step_y: float = hit.position.y - global_position.y
		if step_y > 0.01 and step_y <= step_height:
			global_position.y += step_y


## Handles camera lean left/right via Q and E. Disabled while prone.
func _handle_lean(delta: float) -> void:
	if _is_prone:
		_lean_amount = move_toward(_lean_amount, 0.0, lean_speed * delta)
		camera_target.rotation.z = deg_to_rad(_lean_amount)
		camera_target.position.x = _lean_amount / lean_angle * lean_offset
		return
	var target_lean := 0.0
	if Input.is_action_pressed("lean_left"): target_lean = lean_angle
	elif Input.is_action_pressed("lean_right"): target_lean = -lean_angle
	_lean_amount = lerp(_lean_amount, target_lean, lean_speed * delta)
	camera_target.rotation.z = deg_to_rad(_lean_amount)
	camera_target.position.x = _lean_amount / lean_angle * lean_offset


## Handles mouse look, escape to release mouse, view toggle and zoom input.
func _unhandled_input(event: InputEvent) -> void:
	if event is InputEventMouseMotion:
		if Input.get_mouse_mode() == Input.MOUSE_MODE_CAPTURED:
			_look = -event.relative * mouse_sensitivity
	if event.is_action_pressed("ui_cancel"):
		if Input.get_mouse_mode() == Input.MOUSE_MODE_CAPTURED:
			Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)
		else:
			Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)
